wrf_run/data_fetch/gfs_fetch_curl.sh
wrf_run/data_fetch/gfs_fetch_wget.sh

adjusted fetch adress to compatible data

Fix: GFS Input data path change

---

README.md
wrf_install/README.md
wrf_install/install_wrf.sh
wrf_install/linux/preparations.sh
wrf_install/linux/set_env.sh
wrf_install/wrf_compile/wps_compile.sh
wrf_install/wrf_compile/wrf_compile.sh
wrf_install/wrf_preparation/fortran_bindings.sh
wrf_install/wrf_preparation/install_libraries.sh
wrf_install/wrf_preparation/netcdf.sh

Issue 6: Adjustments for WRF4 installation

---

wrf_install/install_wrf.sh

Adding check for BUILD PATH variable 

---

wrf_deploy/README.md
wrf_deploy/load_wrf.sh

Issue 2: Deployment for WRFV4

---

wrf_deploy/load_packages.sh

Issue 36: WRF Deploy: check for installed yay

---

README.md
additions/config/namelist.input
additions/config/namelist.wps
wrf_deploy/README.md
wrf_deploy/load_packages.sh
wrf_install/wrf_postprocessing/ncl_install.sh
wrf_run/.gitignore
wrf_run/data_fetch/gfs_fetch_curl.sh
wrf_run/data_fetch/gfs_fetch_wget.sh
wrf_run/logs/.gitignore
wrf_run/model_run/pre_processing.sh
wrf_run/model_run/prepare_namelist.sh
wrf_run/model_run/run_preprocessing.sh
wrf_run/post_processing/draw_meteograms.sh
wrf_run/post_processing/draw_plots.sh
wrf_run/run_model.sh
wrf_run/set_env.sh

Issue 18: Run scripts for WRFV4

---

wrf_install/linux/preparations.sh

Issue 11: Install with preloaded libraries

---

additions/config/namelist_low_res.wps
wrf_deploy/README.md
wrf_deploy/deploy_wrf.sh
wrf_deploy/load_geodata.sh
wrf_deploy/load_wrf.sh
wrf_deploy/set_env.sh

Issue 39: change default deployment to WRFV4

---

wrf_install/.gitignore
wrf_install/README.md
wrf_install/install_wrf.sh
wrf_install/linux/basics.sh
wrf_install/linux/preparations.sh
wrf_install/wrf_compile/wps_compile.sh
wrf_install/wrf_compile/wrf_compile.sh
wrf_install/wrf_pre_test/wrf_precompile_tests.sh
wrf_install/wrf_preparation/fortran_bindings.sh
wrf_install/wrf_preparation/install_libraries.sh
wrf_install/wrf_preparation/netcdf.sh

Issue 3: Error Handling / Error Output during Installation

---

wrf_deploy/deploy_wrf.sh
wrf_deploy/load_geodata.sh
wrf_deploy/load_wrf.sh
wrf_deploy/set_env.sh
wrf_install/linux/preparations.sh

Issue 46: WRF deploy environment variables

---

wrf_install/wrf_preparation/netcdf.sh

Issue 49: setenv: command not found

---

wrf_deploy/load_packages.sh
wrf_install/linux/basics.sh
wrf_run/README.md

Issue 51: Fortran could not compile .f90 files

---

plots/plot_timestamp_output
plots/thunderstorm_lib.ncl
wrf_run/data_fetch/gfs_fetch_curl.sh
wrf_run/data_fetch/gfs_fetch_wget.sh
wrf_run/model_run/clean_up_output.sh
wrf_run/model_run/pre_processing.sh
wrf_run/model_run/run_preprocessing.sh
wrf_run/post_processing/draw_meteograms.sh
wrf_run/post_processing/draw_plots.sh
wrf_run/run_model.sh
wrf_run/set_env.sh

Issue 56: WRF Output: NCL blocks error handling

---

wrf_run/data_fetch/gfs_fetch_curl.sh
wrf_run/data_fetch/gfs_fetch_wget.sh
wrf_run/model_run/clean_up_output.sh
wrf_run/model_run/pre_processing.sh
wrf_run/model_run/run_preprocessing.sh
wrf_run/post_processing/draw_meteograms.sh
wrf_run/post_processing/draw_plots.sh
wrf_run/run_model.sh
wrf_run/set_env.sh

Issue 10: Error Handling / Error Output of ncl output

---

wrf_deploy/create_directories.sh
wrf_deploy/deploy_wrf.sh
wrf_deploy/set_env.sh
wrf_install/wrf_postprocessing/upp_compile.sh
wrf_run/create_mail.sh
wrf_run/data_fetch/gfs_fetch.sh
wrf_run/model_run/pre_processing.sh
wrf_run/model_run/prepare_namelist.sh
wrf_run/post_processing/create_ini.sh
wrf_run/post_processing/draw_meteograms.sh
wrf_run/post_processing/draw_plots.sh
wrf_run/run_model.sh

Issue 60: Update: Documentation

---

wrf_run/create_mail.sh
wrf_run/data_fetch/gfs_fetch.sh
wrf_run/data_fetch/gfs_fetch_curl.sh
wrf_run/data_fetch/gfs_fetch_wget.sh
wrf_run/model_run/clean_up_output.sh
wrf_run/model_run/pre_processing.sh
wrf_run/model_run/prepare_namelist.sh
wrf_run/model_run/run_preprocessing.sh
wrf_run/post_processing/create_ini.sh
wrf_run/post_processing/draw_meteograms.sh
wrf_run/post_processing/draw_plots.sh
wrf_run/run_model.sh
wrf_run/set_env.sh

Issue 10: Error Handling / Error Output of ncl output 

---

additions/config/namelist.input

Issue 41: WRF run: adjusting namelist parameter

---

wrf_run/README.md
wrf_run/post_processing/post_hook.sh
wrf_run/run_model.sh

Issue 64: WRF Run: Add Script Posthook

---

wrf_install/install_wrf.sh
wrf_install/linux/basics.sh
wrf_install/linux/preparations.sh
wrf_install/wrf_compile/wps_compile.sh
wrf_install/wrf_compile/wrf_compile.sh
wrf_install/wrf_postprocessing/ncl_install.sh
wrf_install/wrf_postprocessing/upp_compile.sh
wrf_install/wrf_postprocessing/wrf_postprocessing.sh
wrf_install/wrf_pre_test/fortran_tests.sh
wrf_install/wrf_pre_test/wrf_precompile_tests.sh
wrf_install/wrf_preparation/fortran_bindings.sh
wrf_install/wrf_preparation/install_libraries.sh
wrf_install/wrf_preparation/netcdf.sh

Issue 54: WRF Installation: error handling when using -e

---

wrf_deploy/README.md
wrf_install/README.md
wrf_run/README.md
wrf_run/data_fetch/gfs_fetch.sh

Issue 68: WRF Run: gfs data source address has changed

---

wrf_run/run_model.sh
wrf_run/set_env.sh

Issue 7: Error Handling / Error Output during WRF run

---

wrf_install/README.md
wrf_install/install_wrf.sh
wrf_install/linux/basics.sh
wrf_install/linux/set_env.sh
wrf_install/wrf_compile/wps_compile.sh
wrf_install/wrf_compile/wrf_compile.sh
wrf_install/wrf_pre_test/fortran_tests.sh
wrf_install/wrf_pre_test/wrf_precompile_tests.sh
wrf_install/wrf_preparation/fortran_bindings.sh
wrf_install/wrf_preparation/install_libraries.sh
wrf_install/wrf_preparation/netcdf.sh

Issue 26: build path as parameter

---

wrf_deploy/README.md
wrf_deploy/load_geodata.sh
wrf_deploy/load_visualization.sh
wrf_deploy/load_wrf.sh

Issue 77: Fortify deployment process

---

README.md
wrf_deploy/deploy_wrf.sh
wrf_deploy/load_geodata.sh
wrf_deploy/load_wrf.sh
wrf_install/README.md
wrf_install/install_wrf.sh
wrf_install/linux/set_env.sh
wrf_install/wrf_compile/wps_compile.sh
wrf_install/wrf_compile/wrf_compile.sh
wrf_install/wrf_postprocessing/wrf_postprocessing.sh
wrf_install/wrf_preparation/netcdf.sh
wrf_run/README.md
wrf_run/model_run/prepare_namelist.sh
wrf_run/set_env.sh

Issue 74: Support for WRF 4.2.x

---

wrf_run/README.md
wrf_run/data_fetch/gfs_fetch.sh

Issue 28: Make GFS data fetch more robust

---

wrf_deploy/load_wrf.sh
wrf_install/wrf_compile/wps_compile.sh
wrf_install/wrf_compile/wrf_compile.sh
wrf_install/wrf_postprocessing/upp_compile.sh
wrf_run/model_run/prepare_namelist.sh

Issue 33: Set geo data path to namelist.wps

---

wrf_run/README.md
wrf_run/logs/.gitignore
wrf_run/post_processing/draw_meteograms.sh

Issue 85: Handle output generation with no meteogram locations

---

wrf_run/README.md
wrf_run/help/man_help.sh
wrf_run/run_model.sh
wrf_run/set_env.sh
wrf_run/validate/validate_parameter.sh

Issue 23: Dynamic parameter for WRF run

---

README.md

Issue 89: switched to codefactor

---

wrf_install/README.md
wrf_install/help/man_help.sh
wrf_install/install_wrf.sh

Issue 87: Parameter handling wrf install

---

wrf_run/data_fetch/gfs_fetch.sh

change to new gfs data url

---

wrf_run/post_processing/draw_plots.sh

Issue 102: update local storage path for data output

---

README.md
wrf_install/linux/set_env.sh

Issue 108: security update for zlib

---

wrf_run/model_run/run_wrfmodel.sh
wrf_run/post_processing/draw_meteograms.sh
wrf_run/post_processing/draw_plots.sh
wrf_run/run_model.sh

Issue 105: Refine internal logging

---

wrf_run/data_fetch/gfs_fetch.sh

Issue 84: make data fetch more resilient

---

wrf_run/README.md
wrf_run/help/man_help.sh
wrf_run/run_model.sh

Issue 100: storage option for model run

---

wrf_deploy/load_wrf.sh

Issue 113: Remove syntax error from previous switch case

---

wrf_run/environment/set_model_env.sh
wrf_run/model_run/run_wrfmodel.sh

Issue 116: run scripts for WRFV4.4

---

wrf_deploy/deploy_wrf.sh
wrf_deploy/help/man_help.sh
wrf_deploy/linux/load_packages.sh
wrf_deploy/linux/set_env.sh
wrf_deploy/post_processing/check_deployment.sh
wrf_deploy/post_processing/clean_up.sh
wrf_deploy/visualization/load_visualization.sh
wrf_deploy/wrf/load_geodata.sh
wrf_deploy/wrf/load_wrf.sh

Issue 120: Rework deployment script directory structure

---

wrf_run/README.md
wrf_run/data_fetch/gfs_fetch.sh

Issue 122: add ftp fallback
